#!/usr/bin/env bash
# ShipMate — Generate scoped .env for sandbox isolation.
# Copies only project-relevant variables, drops everything else.
#
# Usage: ./setup/generate-scoped-env.sh [--input .env] [--output .env.scoped]

set -euo pipefail

INPUT=".env"
OUTPUT=".env.scoped"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input) INPUT="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ ! -f "$INPUT" ]]; then
  echo "Error: $INPUT not found"
  exit 1
fi

# Only these prefixes/names are allowed into the sandbox
ALLOWED_PATTERNS=(
  "^SHIPMATE_SCOPE_"
  "^GITHUB_TOKEN="
  "^GITLAB_TOKEN="
  "^GITLAB_HOST="
  "^JIRA_BASE_URL="
  "^JIRA_API_TOKEN="
  "^JIRA_USER_EMAIL="
  "^SENTRY_URL="
  "^SENTRY_AUTH_TOKEN="
  "^SENTRY_ORG="
  "^SENTRY_PROJECT="
  "^GRAFANA_URL="
  "^GRAFANA_TOKEN="
  "^SHIPMATE_WORKSPACE="
)

{
  echo "# Auto-generated by generate-scoped-env.sh — DO NOT EDIT"
  echo "# Only project-scoped variables. No host credentials."
  echo "# Source: $INPUT"
  echo ""

  while IFS= read -r line; do
    # Skip comments and empty lines
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue

    for pattern in "${ALLOWED_PATTERNS[@]}"; do
      if [[ "$line" =~ $pattern ]]; then
        echo "$line"
        break
      fi
    done
  done < "$INPUT"
} > "$OUTPUT"

VAR_COUNT=$(grep -c "=" "$OUTPUT" 2>/dev/null || echo "0")
echo "Generated $OUTPUT ($VAR_COUNT variables from $INPUT)"
